### ISSUE TITLE
missing programs in the `spike` / `simple` targets ?

### ISSUE THREAD

**Issue by eflaner** [toddmaustin/bringup-bench#8]
- satomi program is missing in BMARKS. was that intentional ? 
- almost 10 programs were missing in the TARGET_BMARKS of `spike`/`simple` target. 
I have mentioned below the missing programs.
1. ackermann
2. anagram
3. c-interp
4. checkers
5. donut
6. lz-compress
7. pi-calc
8. quine
9. rho-factor
10. spelt2num 

Any specific reason why these were omitted ?

**Comment by toddmaustin** [comment]
They still need debugging on those targets, or they are too large for the small memory models. I'm slowly working through them, thanks for the note!
